services:
  backend:
    build: ./backend
    ports:
      - '5000:5000'
    networks:
      - app-network
    volumes:
      - ./backend:/usr/src/app

  frontend:
    build: ./frontend
    ports:
      - '8080:80'
    networks:
      - app-network
    volumes:
      - ./frontend:/app

networks:
  app-network:
    driver: bridge